import os

SPREADSHEET_ID = os.environ.get("SPREADSHEET_ID", "1WAYfEypyx5cIOOzP9zM-X2HQapsD_IqeMD7YbiG1er4")
SHEET_NAME = os.environ.get("SHEET_NAME", "Sheet2")

COL_SESSION_ID = 2
COL_LINK = 8
COL_STATUS = 12
COL_REASON = 13
COL_CHECKED_AT = 23
COL_VIDEO_DUR = 9
COL_UPLOAD_DATE = 25
