main:
  params: [args]
  steps:

    - init:
        assign:
          - project: "tbrain-services"
          - region: "asia-southeast1"
          - recheck_all: ${default(map.get(args, "recheck_all"), "")}
          - recheck_fail: ${default(map.get(args, "recheck_fail"), "")}

    - run_sheet_qc:
        call: googleapis.run.v1.namespaces.jobs.run
        args:
          name: ${"namespaces/" + project + "/jobs/tbrain-games-qc-job"}
          location: ${region}
          body:
            overrides:
              containerOverrides:
                - env:
                    - name: RECHECK_ALL
                      value: ${recheck_all}
                    - name: RECHECK_FAIL
                      value: ${recheck_fail}
        result: result

    - done:
        return: "Sheet QC completed"
